### ISSUE TITLE
Does not work with IntelliJ 2023.1

### ISSUE THREAD

**Issue by thomasmuders-imtf** [binxio/cfn-lint-plugin#31]
The plugin does not work with IntelliJ 2023.1. It is shown as incompatible with the version.

**Comment by pheck** [comment]
Hope I'm not violating any terms & conditions with this, but since the plugin's compatibility with the 2023.1-IDE's seems fixed (all credits to @zfil & @mvanholsteijn) but it's not yet published on Jetbrains Marketplace, I used these instructions to build it & install it manually. 

Maybe this is useful to others.

```sh
# 1. download & build 
mkdir -p /tmp/cfnlint
cd /tmp/cfnlint
git clone https://github.com/binxio/cfn-lint-plugin.git
docker run --rm -v $(pwd):/tmp -w /tmp/cfn-lint-plugin gradle:8-jdk17-alpine gradle build -x publishPlugin -PintellijPublishToken=stopbuggingme -Pversion=0.1.26
# 2. PhpStorm: install plugin from disk... -> /tmp/cfnlint/cfn-lint-plugin/build/distributions/cfn-lint-plugin-0.1.26.zip
```

**Comment by zfil** [comment]
Yeah the plugin works with the current intellij build.
But I need to upgrade a couple of things in orders to be able to have it published, but it is a bit hard to find time currently.

**Comment by zfil** [comment]
I've made a new PR that should fix publication and fix other stuff

**Comment by thomasmuders-imtf** [comment]
> I've made a new PR that should fix publication and fix other stuff

for me this fixed the issue (I compiled and tested locally with latest Intellij Version)
